"""Mean-reversion backtest engine.

The engine is filesystem-location independent and treats generated backtest
artifacts as outputs rather than repository source files.
"""

from __future__ import annotations

import json
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parent.parent
ALERT_CSV = PROJECT_ROOT / "alerts" / "alerts_output.csv"
BACKTEST_DIR = PROJECT_ROOT / "backtest"
RESULTS_CSV = BACKTEST_DIR / "backtest_results.csv"
METRICS_JSON = BACKTEST_DIR / "backtest_metrics.json"
PNL_PLOT = BACKTEST_DIR / "pnl_curve.png"

POSITION_SIZE = 1.0
NOTIONAL_PER_UNIT = 1000.0
FEE_PER_TRADE = 0.5
SLIPPAGE_PCT = 0.0005
ENTRY_ON_EDGE = True
ANNUAL_TRADING_DAYS = 252


def ensure_dirs():
    BACKTEST_DIR.mkdir(parents=True, exist_ok=True)


def load_alerts(path=ALERT_CSV):
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(f"Alerts CSV not found at: {path}")
    df = pd.read_csv(path)
    required = {"timestamp", "spread", "signal"}
    missing = required - set(df.columns)
    if missing:
        raise ValueError(f"Required columns missing: {sorted(missing)}")
    df["timestamp"] = pd.to_datetime(df["timestamp"], utc=True, errors="coerce")
    df["spread"] = pd.to_numeric(df["spread"], errors="coerce")
    df["signal"] = df["signal"].astype(str).str.upper()
    df = df.dropna(subset=["timestamp", "spread"]).sort_values("timestamp").reset_index(drop=True)
    return df


def infer_periods_per_day(df):
    if len(df) < 3:
        return 1.0
    deltas = df["timestamp"].diff().dt.total_seconds().dropna()
    median_seconds = deltas.median()
    if not median_seconds or median_seconds <= 0:
        return 1.0
    return max(1.0, 86400.0 / median_seconds)


def simulate_backtest(df, position_size=POSITION_SIZE, notional_per_unit=NOTIONAL_PER_UNIT,
                      fee_per_trade=FEE_PER_TRADE, slippage_pct=SLIPPAGE_PCT,
                      entry_on_edge=ENTRY_ON_EDGE):
    df = df.copy().reset_index(drop=True)
    mapping = {"LONG": float(position_size), "SHORT": -float(position_size), "HOLD": 0.0}
    df["desired_pos"] = df["signal"].map(mapping).fillna(0.0)
    df["position"] = 0.0

    for i in range(len(df)):
        prev_pos = df.at[i - 1, "position"] if i else 0.0
        prev_signal = df.at[i - 1, "signal"] if i else "HOLD"
        curr_signal = df.at[i, "signal"]
        desired = df.at[i, "desired_pos"]
        position = prev_pos

        if not entry_on_edge:
            position = desired
        elif (prev_signal == "HOLD" or prev_pos == 0.0) and curr_signal in ("LONG", "SHORT"):
            position = desired
        elif curr_signal == "HOLD" and prev_pos != 0.0:
            position = 0.0
        elif prev_pos != 0.0 and curr_signal in ("LONG", "SHORT") and np.sign(desired) != np.sign(prev_pos):
            position = desired

        df.at[i, "position"] = position

    df["spread_prev"] = df["spread"].shift(1)
    df["spread_diff"] = (df["spread"] - df["spread_prev"]).fillna(0.0)
    df["position_prev"] = df["position"].shift(1).fillna(0.0)
    df["cash_pnl_raw"] = df["position_prev"] * df["spread_diff"] * float(notional_per_unit)
    df["pos_change"] = (df["position"] - df["position_prev"]).abs()
    df["trade_cost"] = (float(fee_per_trade) + float(slippage_pct) * float(notional_per_unit)) * df["pos_change"]
    df["pnl"] = df["cash_pnl_raw"] - df["trade_cost"]
    df["cum_pnl"] = df["pnl"].cumsum()

    columns = ["timestamp", "x_price", "y_price", "beta_kalman", "spread", "signal",
               "desired_pos", "position", "position_prev", "spread_diff",
               "cash_pnl_raw", "trade_cost", "pnl", "cum_pnl"]
    return df[[c for c in columns if c in df.columns]]


def _extract_trades(df):
    """Extract complete trades using the cashflow bar that closes the position."""
    trades = []
    positions = df["position"].to_numpy()
    pnls = df["pnl"].to_numpy()
    timestamps = df["timestamp"].to_numpy()
    in_trade = False
    entry_idx = None
    entry_pos = 0.0
    acc_pnl = 0.0

    for i, current in enumerate(positions):
        if not in_trade and current != 0.0:
            in_trade = True
            entry_idx = i
            entry_pos = current
            acc_pnl = 0.0

        if not in_trade:
            continue

        # PnL at row i is generated by position_prev, so when the current
        # position becomes zero this row is the position's exit cashflow.
        acc_pnl += pnls[i]
        prev_pos = positions[i - 1] if i > 0 else 0.0
        closes_trade = (
            i > entry_idx
            and prev_pos != 0.0
            and current == 0.0
        )
        reverses_trade = (
            i > entry_idx
            and prev_pos != 0.0
            and current != 0.0
            and np.sign(current) != np.sign(prev_pos)
        )

        if closes_trade or reverses_trade:
            trades.append({
                "entry_idx": int(entry_idx),
                "exit_idx": int(i),
                "entry_ts": str(timestamps[entry_idx]),
                "exit_ts": str(timestamps[i]),
                "position": float(entry_pos),
                "trade_pnl": float(acc_pnl),
            })
            if reverses_trade:
                entry_idx = i
                entry_pos = current
                acc_pnl = 0.0
                continue
            in_trade = False

    return trades


def compute_metrics(df):
    total_pnl = float(df["cum_pnl"].iloc[-1]) if len(df) else 0.0
    returns = df["pnl"].fillna(0.0)
    periods_per_day = infer_periods_per_day(df)
    annual_factor = np.sqrt(ANNUAL_TRADING_DAYS * periods_per_day)
    std = returns.std(ddof=1)
    sharpe = (returns.mean() / std) * annual_factor if std and std > 0 else None
    running_max = df["cum_pnl"].cummax()
    max_drawdown = float((df["cum_pnl"] - running_max).min()) if len(df) else 0.0
    trades = _extract_trades(df)
    n = len(trades)
    win_rate = sum(t["trade_pnl"] > 0 for t in trades) / n if n else None
    avg_trade = sum(t["trade_pnl"] for t in trades) / n if n else 0.0
    return {
        "total_pnl": total_pnl,
        "sharpe": float(sharpe) if sharpe is not None else None,
        "max_drawdown": max_drawdown,
        "n_trades": n,
        "win_rate": float(win_rate) if win_rate is not None else None,
        "avg_trade_pnl": float(avg_trade),
        "periods_per_day_est": float(periods_per_day),
        "trades_sample": trades[:50],
    }


def plot_pnl_curve(df, path=PNL_PLOT):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    fig, ax = plt.subplots(figsize=(10, 5))
    ax.plot(df["timestamp"], df["cum_pnl"])
    ax.set(xlabel="Time", ylabel="Cumulative PnL ($)", title="Backtest — Cumulative PnL")
    ax.grid(True)
    fig.tight_layout()
    fig.savefig(path)
    plt.close(fig)


def save_results(df, metrics):
    ensure_dirs()
    df.to_csv(RESULTS_CSV, index=False)
    METRICS_JSON.write_text(json.dumps(metrics, indent=2, default=str), encoding="utf-8")


def print_summary(metrics):
    print("\nBacktest Summary")
    print("-------------------------------")
    print(f"Total PnL      : ${metrics['total_pnl']:.6f}")
    print(f"Sharpe (ann.)  : {metrics['sharpe']}")
    print(f"Max Drawdown   : ${metrics['max_drawdown']:.6f}")
    print(f"Number Trades  : {metrics['n_trades']}")
    print(f"Win Rate       : {metrics['win_rate']}")
    print(f"Avg Trade PnL  : ${metrics['avg_trade_pnl']:.6f}")
    print("-------------------------------\n")


def main():
    ensure_dirs()
    alerts = load_alerts()
    results = simulate_backtest(alerts)
    metrics = compute_metrics(results)
    save_results(results, metrics)
    plot_pnl_curve(results)
    print_summary(metrics)
    return results, metrics


if __name__ == "__main__":
    main()
